const $=id=>document.getElementById(id);
let snapshot=null, generation=0, offset=0, currentAsset=null, busy=false;
const labels={healthy:'Live aktif',stale:'Data terlambat',waiting:'Menunggu data',degraded:'Listener bermasalah','catching-up':'Mengejar head','recovering-history':'Live aktif · recovery histori'};
const short=s=>s.length>24?s.slice(0,10)+'…'+s.slice(-8):s;
const num=n=>n==null?'—':Number(n).toLocaleString('id-ID');
const stamp=s=>s?new Date(s).toLocaleString('id-ID'):'—';
function node(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;}
function route(){const hash=location.hash.slice(1);const detail=hash.startsWith('candidate/');const view=detail?'detail':hash==='health'?'health':'radar';const asset=detail?hash.slice(10):null;if(asset!==currentAsset){currentAsset=asset;offset=0;}for(const v of ['radar','detail','health'])$(v).hidden=v!==view;$('title').textContent={radar:'Onchain radar',detail:'Detail kandidat',health:'Data health'}[view];$('nav-radar').classList.toggle('active',view!=='health');$('nav-health').classList.toggle('active',view==='health');load();}
function renderRadar(){if(!snapshot)return;const h=snapshot.health;$('candidates-count').textContent=num(h.candidates_in_sample||0);$('events-count').textContent=num(h.events_in_sample||0);$('checkpoint').textContent=num(h.cursor);$('lag').textContent=num(h.lag_blocks);const query=$('search').value.trim().toLowerCase(),filter=$('filter').value;const rows=snapshot.candidates.filter(c=>(filter==='all'||c.kind===filter)&&c.id.includes(query));$('rows').replaceChildren();$('result-count').textContent=rows.length+' kandidat';$('empty').hidden=rows.length>0;rows.forEach((c,i)=>{const tr=node('tr'),rank=node('td',String(i+1)),asset=node('td'),a=node('a',short(c.id)),value=c.conviction_score==null?'—':String(c.conviction_score),score=node('strong',value,'score '+(c.conviction_score>=70?'hot':c.conviction_score>=45?'warm':''));a.href='#candidate/'+c.id;asset.append(a,node('small',`Activity ${c.activity_score} · ${c.protocol}`));const scoreCell=node('td');scoreCell.append(score,node('small','activity '+c.activity_score));tr.append(rank,asset,scoreCell,node('td',c.safety_score==null?'unknown':`${c.safety_score} · ${c.safety_status}`),node('td',`${c.unique_senders} / ${c.unique_buyers}`),node('td',`${c.buys} / ${c.sells}`),node('td',c.activity_acceleration+'×'),node('td',c.verdict));$('rows').append(tr);});}
function renderHealth(h){$('connection').textContent=labels[h.state]||h.state;$('connection').classList.toggle('warn',['stale','waiting','degraded','catching-up'].includes(h.state));$('health-summary').textContent=h.reason||({healthy:'Listener live aktif.',stale:'Heartbeat lebih dari 60 detik. Periksa log listener dan koneksi RPC.',degraded:'Pembacaan gagal; checkpoint dipertahankan sampai sumber kembali tersedia.','catching-up':'Listener aktif, tetapi checkpoint masih tertinggal dari head.','recovering-history':'Event live aktif sambil celah koneksi dipulihkan.'}[h.state]||'Menunggu data.');$('health-grid').replaceChildren();for(const [label,value] of [['Chain ID','4663'],['Status listener',h.status||'Belum tersedia'],['Transport',h.transport||'HTTP scan'],['Checkpoint',num(h.cursor)],['Head terakhir',num(h.head)],['Jarak head',num(h.lag_blocks)+' blok'],['Recovery histori',num(h.recovery_blocks)+' blok'],['Start observasi',num(h.start)],['Heartbeat',stamp(h.heartbeat)],['Commit terakhir',stamp(h.last_success)],['Reorg terakhir',stamp(h.last_reorg)],['Decode errors (sampel)',num(h.decode_errors_in_sample||0)],['Error terakhir (historis)',h.last_error||'Tidak tercatat'],['Cakupan sampel','5.000 event terbaru']]){const card=node('article',null,'health-card');card.append(node('span',label),node('strong',value));$('health-grid').append(card);}}
function renderDetail(data){$('asset-id').textContent=currentAsset;$('timeline').replaceChildren();if(!data.events.length)$('timeline').append(node('div','Belum ada event untuk kandidat ini. Periksa alamat atau tunggu data masuk.','empty'));for(const e of data.events){const card=node('article',null,'event'),head=node('div',null,'event-head');head.append(node('strong',e.name),node('span',`Blok ${num(e.block_number)} · ${stamp(e.observed_at)}`));const evidence=node('a','Lihat transaksi ↗');evidence.href=e.explorer_url;evidence.target='_blank';evidence.rel='noopener noreferrer';card.append(head,node('pre',JSON.stringify(e.decoded,null,2)),evidence);if(e.decode_error)card.append(node('p',e.decode_error));$('timeline').append(card);}$('more').hidden=!data.has_more;}
async function load(){const ticket=++generation;const asset=currentAsset;busy=true;$('refresh').disabled=true;try{const q=asset?'?asset='+encodeURIComponent(asset)+'&offset='+offset:'';const res=await fetch('/api/radar'+q,{cache:'no-store'});if(!res.ok)throw new Error('Server data belum tersedia ('+res.status+'). Coba refresh.');const data=await res.json();if(ticket!==generation)return;snapshot=data;$('error').hidden=true;renderHealth(data.health);renderRadar();if(asset)renderDetail(data);$('updated').textContent='Diperbarui '+new Date().toLocaleTimeString('id-ID');}catch(e){if(ticket!==generation)return;$('error').textContent=e.message;$('error').hidden=false;$('connection').textContent='Koneksi terputus';$('connection').classList.add('warn');}finally{if(ticket===generation){busy=false;$('refresh').disabled=false;}}}
$('refresh').onclick=load;$('search').oninput=renderRadar;$('filter').onchange=renderRadar;$('more').onclick=()=>{offset+=100;load();};window.addEventListener('hashchange',route);setInterval(()=>{if(!busy&&!document.hidden)load();},10000);route();
